In [1]:
import numpy as np

#### Vector-Vector Multiplication

In [2]:
def vector_vector_multiplication(u, v):
    # Making sure the two vectors are of the same shape
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + (u[i] * v[i])

    return result

In [6]:
np.random.seed(42)
u = np.random.randint(low=10, high=100, size=(5, 1))
v = np.random.randint(low=10, high=100, size=(5, 1))
u, v

(array([[61],
        [24],
        [81],
        [70],
        [30]]),
 array([[92],
        [96],
        [84],
        [84],
        [97]]))

In [7]:
vector_vector_multiplication(u, v)

array([23510.])

This can be easily be implemented in numpy, but you must get the Transpose of the 1st array

In [19]:
np.dot(u.T, v)

array([[23510]])

#### Matrix-Vector Multiplication

In [14]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    no_of_rows = U.shape[0]
    result = np.zeros(no_of_rows)

    for i in range(no_of_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [23]:
U = np.random.randint(low=10, high=100, size=(5, 5))
U

array([[56, 44, 87, 90, 45],
       [59, 13, 11, 15, 63],
       [13, 63, 72, 27, 99],
       [53, 43, 83, 71, 23],
       [57, 24, 81, 87, 96]])

In [15]:
matrix_vector_multiplication(U, v)

/tmp/ipykernel_13557/1222081259.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  result[i] = vector_vector_multiplication(U[i], v)


array([13067., 24621., 26395., 27791., 29759.])

This can also be achieved using numpy.No need of Transpose for this case

In [20]:
np.dot(U, v)

array([[13067],
       [24621],
       [26395],
       [27791],
       [29759]])

#### Matrix-Matrix Multiplication

In [21]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]  # Get the column i values
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [26]:
V = np.random.randint(low=10, high=100, size=(5, 2))
V

array([[17, 44],
       [44, 42],
       [14, 50],
       [37, 16],
       [82, 81]])

In [27]:
U.shape, V.shape

((5, 5), (5, 2))

In [28]:
matrix_matrix_multiplication(U, V)

array([[11126., 13747.],
       [ 7450.,  9035.],
       [13118., 15269.],
       [ 8468., 11287.],
       [14250., 16734.]])

This can also be achieved using numpy

In [29]:
np.dot(U, V)

array([[11126, 13747],
       [ 7450,  9035],
       [13118, 15269],
       [ 8468, 11287],
       [14250, 16734]])